### ISSUE TITLE
Rewrite relative url paths

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-npm#16]
This is probably over-simplified, but something like this…

components/a.css:

``` css
.a { background: url("a.png"); }
```

components/b.css:

``` css
.b { background: url("b.png"); }
```

both.css:

``` css
@import "components/a.css";
@import "components/b.css";
```

output (desired):

``` css
.a { background: url("components/a.png"); }
.b { background: url("components/b.png"); }
```
